#include <stdint.h>
#include "exception.h"
#include "mbox.h"
#include "thread.h" 
#include "io.h"
#include "mini_uart.h"
#include "timer.h"
#include "printf.h"
#include "utils.h"
#include "thread.h"
#include "syscall.h"

void enable_interrupt() { asm volatile("msr DAIFClr, 0xf"); }
void disable_interrupt() { asm volatile("msr DAIFSet, 0xf"); }

void currentEL_ELx_sync_handler() {
  printf("[sync_handler_currentEL_ELx]\n");

  uint64_t spsr_el1, elr_el1, esr_el1;
  asm volatile("mrs %0, spsr_el1" : "=r"(spsr_el1));
  asm volatile("mrs %0, elr_el1" : "=r"(elr_el1));
  asm volatile("mrs %0, esr_el1" : "=r"(esr_el1));
  printf("[SPSR_EL1]: 0x%08x\n", spsr_el1);
  printf("[ELR_EL1]: 0x%08x\n", elr_el1);
  printf("[ESR_EL1]: 0x%08x\n", esr_el1);
  int ec = (esr_el1 >> 26) & 0x3f; // exception class
  printf("[ec]: %d\n", ec);
  if(ec == 37){
    printf("[PID]: %d\n", get_current()->pid);
    printf("[ERROR]: MMU faults generated by data accesses\n");
  }

  while(1){}
  // 0x96000000 = 10010110000000000000000000000000
}

void lower_64_EL_sync_handler(uint64_t sp){

  // printf("trap frame sp: %x\n", sp);

  // exception registor
  uint64_t spsr_el1, elr_el1, esr_el1;
  asm volatile("mrs %0, spsr_el1" : "=r"(spsr_el1));
  asm volatile("mrs %0, elr_el1" : "=r"(elr_el1));
  asm volatile("mrs %0, esr_el1" : "=r"(esr_el1));

  // https://developer.arm.com/documentation/ddi0595/2021-06/AArch64-Registers/ESR-EL1--Exception-Syndrome-Register--EL1-

  int ec = (esr_el1 >> 26) & 0x3f; // exception class

  if(ec == 0b010101){
    // according the lab spec, the number of the systme call is store in x8
    trap_frame_t *trap_frame = (trap_frame_t *)sp;

    int syscall_number;
    asm volatile("mov %0, x8" : "=r"(syscall_number));

    syscall_handler(syscall_number, trap_frame);
  }
  //printf("pid %d done exception handling\n", get_current());
}

// user timer handler
void el0_to_el1_irq_handler() {
  disable_interrupt();
  uint32_t is_uart = (*IRQ_PENDING_1 & AUX_IRQ);
  uint32_t is_core_timer = (*CORE0_IRQ_SOURCE & CNTPNS_IRQ);
  //printf("is_core_timer: %d\n", is_core_timer);
  if (is_uart) {
    uart_handler();
  } else if(is_core_timer) {
    timer_schedular_handler();
  }
  enable_interrupt();
}

// kernel timer handler
uint64_t el1_to_el1_irq_handler(uint64_t sp) {
  disable_interrupt();
  uint32_t is_uart = (*IRQ_PENDING_1 & AUX_IRQ);
  uint32_t is_core_timer = (*CORE0_IRQ_SOURCE & CNTPNS_IRQ);
  //printf("kernel:is_core_timer: %d\n", is_core_timer);
  if (is_uart) {
    uart_handler();
  } else if(is_core_timer) {
    schedule();
  }
  //plan_next_interrupt_tval(SCHEDULE_TVAL);
  enable_interrupt();
  return sp;
}

void default_handler() { print_s("===== default handler =====\n"); }